[project]
name = "git-nexus"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "markdown>=3.10",
    "requests>=2.32.5",
]
